In [14]:
import pandas as pd

In [24]:
df=pd.read_csv('gpareport23.csv')
df

,"AVERAGE Semester UNDERGRADUATE GRADE POINT AVERAGES\nUNIVERSITY OF WISCONSIN-MADISON\nFIRST SEMESTER 2023-2024\nJun 18, 2024",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,Grade point average is calculated by dividing ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Letter Grades A = Excellent\nAB = Intermediate...,NaN,Grade Points Per Credit\n4.0\n3.5\n3.0\n2.5\n2...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Only the letter grades A, AB, B, BC, C, D, and...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,This report prepared by the Office of the Regi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,FRESHMEN,NaN,NaN,NaN,NaN,SOPHOMORES,NaN,NaN,JUNIORS SENIORS ...,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Nursing Undergraduate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80,3.612,192,3.719,272,3.685
262,Pre-Nursing,NaN,157.0,NaN,3.266,NaN,165,3.378,NaN,85,3.490,7,3.282,414,3.356
263,Pharmacy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,3.668,16,3.547,28,3.598
264,Pharmacology & Toxicology,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,3.668,16,3.547,28,3.598
265,Total,NaN,3043.0,NaN,3.391,NaN,4517,3.428,NaN,5181,3.496,6006,3.603,18747,3.496

In [10]:
with open('gpareport23.csv', 'r', encoding='utf-8', errors='ignore') as file:
    content = file.read()  # Read the entire content of the file

# Split content by newline character
lines = content.split('\n')

# Print the first few lines
for i, line in enumerate(lines[:266]):  # Show the first 10 lines
    print(f"Line {i+1}: {line}")
gpa

Line 1: "AVERAGE Semester UNDERGRADUATE GRADE POINT AVERAGES
Line 2: UNIVERSITY OF WISCONSIN-MADISON
Line 3: FIRST SEMESTER 2023-2024
Line 4: Jun 18, 2024",,,,,,,,,,,,,,
Line 5: "Grade point average is calculated by dividing the number of grade points earned by the number of credits carried, with grade points being awarded as follows:",,,,,,,,,,,,,,
Line 6: ,"Letter Grades A = Excellent
Line 7: AB = Intermediate B = Good
Line 8: BC = Intermediate
Line 9: C = Fair
Line 10: D = Poor
Line 11: F = Failure",,"Grade Points Per Credit
Line 12: 4.0
Line 13: 3.5
Line 14: 3.0
Line 15: 2.5
Line 16: 2.0
Line 17: 1.0
Line 18: 0.0",,,,,,,,,,,
Line 19: "Only the letter grades A, AB, B, BC, C, D, and F are considered in the compilation of this report. Should grades other than these appear on a student's record, the credits for these grades are subtracted from the total number of credits, with no grade points being awarded.
Line 20: Prior to September 1954, the following grade points per credit were awarded:  A (3), B (2), C (1), D (0), E (-l/2), and F (-1).
Line 21: Please note: In order to protect student privacy, average GPA for groups of five or fewer students has been redacted.",,,,,,,,,,,,,,
Line 22: This report prepared by the Office of the Registrar.,,,,,,,,,,,,,,
Line 23: FRESHMEN,,,,,SOPHOMORES,,,JUNIORS              SENIORS                   TOTAL,,,,,,
Line 24: Count,,,,GPA,,Count,GPA,,Count,GPA,Count,GPA,Count,GPA
Line 25: Undergraduate Men and  Women,,,,,,,,,,,,,,
Line 26: Total,,5411,,3.350,,8464,3.403,,9709,3.444,11755,3.541,35339,3.451
Line 27: Men,,2368,,3.298,,3947,3.373,,4528,3.384,5749,3.475,16592,3.400
Line 28: Women,,3043,,3.391,,4517,3.428,,5181,3.496,6006,3.603,18747,3.496
Line 29: Undergraduate Men and Women by School/College,,,,,,,,,,,,,,
Line 30: Total,,5411,,3.350,,8464,3.403,,9709,3.444,11755,3.541,35339,3.451
Line 31: Agricultural and Life Sciences,,403,,3.316,,632,3.285,,882,3.339,1100,3.456,3017,3.366
Line 32: Business,,427,,3.352,,826,3.408,,1083,3.428,1323,3.533,3659,3.452
Line 33: Education,,372,,3.452,,454,3.505,,600,3.673,654,3.711,2080,3.609
Line 34: Engineering,,617,,3.228,,1173,3.303,,1074,3.322,1796,3.516,4660,3.377
Line 35: Human Ecology,,269,,3.423,,521,3.509,,753,3.567,747,3.607,2290,3.550
Line 36: Letters and Science,,3151,,3.365,,4666,3.424,,5097,3.443,5783,3.534,18697,3.452
Line 37: Nursing,,172,,3.276,,192,3.350,,203,3.537,323,3.645,890,3.469
Line 38: Pharmacy,,,,,,,,,17,3.637,29,3.584,46,3.604
Line 39: Undergraduate Men by School/College,,,,,,,,,,,,,,
Line 40: Total,,2368,,3.298,,3947,3.373,,4528,3.384,5749,3.475,16592,3.400
Line 41: Agricultural and Life Sciences,,115,,3.217,,164,3.347,,266,3.329,353,3.387,898,3.340
Line 42: Business,,239,,3.354,,470,3.405,,594,3.442,722,3.500,2025,3.444
Line 43: Education,,99,,3.306,,86,3.371,,117,3.578,152,3.607,454,3.489
Line 44: Engineering,,449,,3.200,,827,3.295,,805,3.324,1279,3.509,3360,3.367
Line 45: Human Ecology,,56,,3.193,,136,3.397,,239,3.396,256,3.461,687,3.403
Line 46: Letters and Science,,1395,,3.332,,2237,3.400,,2471,3.385,2918,3.456,9021,3.402
Line 47: Nursing,,15,,3.371,,27,3.171,,31,3.481,56,3.575,129,3.433
Line 48: Pharmacy,,,,,,,,,5,,13,3.630,18,3.612
Line 49: Undergraduate Women by School/College,,,,,,,,,,,,,,
Line 50: Total,,3043,,3.391,,4517,3.428,,5181,3.496,6006,3.603,18747,3.496
Line 51: Agricultural and Life Sciences,,288,,3.356,,468,3.264,,616,3.343,747,3.488,2119,3.377
Line 52: Business,,188,,3.351,,356,3.412,,489,3.410,601,3.575,1634,3.463
Line 53: Education,,273,,3.505,,368,3.535,,483,3.696,502,3.743,1626,3.642
Line 54: Engineering,,168,,3.306,,346,3.323,,269,3.318,517,3.534,1300,3.402
Line 55: Human Ecology,,213,,3.484,,385,3.546,,514,3.642,491,3.680,1603,3.610
Line 56: Letters and Science,,1756,,3.391,,2429,3.446,,2626,3.497,2865,3.610,9676,3.498
Line 57: Nursing,,157,,3.266,,165,3.378,,172,3.547,267,3.660,761,3.475
Line 58: Pharmacy,,,,,,,,,12,3.668,16,3.547,28,3.598
Line 59: FRESHMEN      SOPHOMORES         JUNIORS              SENIORS                   TOTAL,,,,,,,,,,,,,,
Line 60: Count,,,,GPA,,Count,GPA,,Count,GPA,Count,GPA,Count,GPA
Line 61: School/College Program         Undergraduate Men and Women by School/College,,,,,,,,,,,,,,
Line 62: Agricultural and Life Sciences,,403,,3.316,,632,3.285,,882,3.339,1100,3.456,3017,3.366
Line 63: Agricultural & Life Sciences,,373,,3.311,,586,3.305,,776,3.362,975,3.471,2710,3.381
Line 64: Agricultural Business Mgmt,,7,,3.199,,8,2.746,,19,3.070,15,3.204,49,3.067
Line 65: Biological Systems Engineering,,10,,3.307,,8,3.099,,38,3.073,63,3.196,119,3.157
Line 66: Dietetics,,13,,3.543,,30,3.082,,49,3.279,47,3.566,139,3.357
Line 67: Business,,427,,3.352,,826,3.408,,1083,3.428,1323,3.533,3659,3.452
Line 68: Business Online,,,,,,8,3.429,,46,3.162,31,3.510,85,3.304
Line 69: Business Undergraduate,,427,,3.352,,818,3.408,,1037,3.436,1292,3.534,3574,3.455
Line 70: Education,,372,,3.452,,454,3.505,,600,3.673,654,3.711,2080,3.609
Line 71: Art,,47,,3.568,,59,3.660,,63,3.738,75,3.755,244,3.692
Line 72: Art Education,,,,,,,,,8,3.554,19,3.729,27,3.678
Line 73: Bachelor of Fine Arts,,,,,,,,,,,12,3.903,12,3.903
Line 74: Bachelor of Fine Arts - Dance,,1,,,,,,,1,,3,,5,
Line 75: Bachelor of Science - Dance,,20,,3.731,,15,3.413,,5,,13,3.836,53,3.664
Line 76: Education Studies,,20,,3.158,,18,3.510,,18,3.656,43,3.651,99,3.532
Line 77: Elementary Education,,,,,,1,,,118,3.941,112,3.912,231,3.926
Line 78: Elementary Special Education,,,,,,,,,,,24,3.966,24,3.966
Line 79: Health Promo and Health Equity,,18,,3.535,,48,3.492,,95,3.654,97,3.586,258,3.591
Line 80: Kinesiology,,,,,,2,,,104,3.497,155,3.603,261,3.555
Line 81: Kines-Pre-Exer/Pre-Mtr Behvr,,146,,3.384,,133,3.356,,78,3.529,7,3.230,364,3.402
Line 82: Phy Ed - Pre-Phy Ed Tchr Prep,,3,,,,1,,,,,,,4,
Line 83: Physical Education,,1,,,,5,,,13,3.277,19,3.633,38,3.439
Line 84: Pre-Art Education,,4,,,,7,3.642,,8,3.729,2,,21,3.654
Line 85: Pre-ElemEdu Spec Edu,,2,,,,1,,,,,,,3,
Line 86: Pre-Elementary Education,,75,,3.426,,103,3.566,,18,3.664,,,196,3.524
Line 87: Pre-Special Educ & Rehab Psy,,9,,3.720,,15,3.743,,3,,,,27,3.739
Line 88: Rehabilitation Psychology,,11,,3.557,,33,3.634,,41,3.666,39,3.730,124,3.666
Line 89: Secondary Education,,1,,,,2,,,8,3.803,11,3.763,22,3.748
Line 90: Special Education,,,,,,,,,10,3.550,7,3.885,17,3.677
Line 91: Theatre & Drama,,14,,3.647,,11,3.497,,9,3.616,16,3.601,50,3.594
Line 92: Engineering,,617,,3.228,,1173,3.303,,1074,3.322,1796,3.516,4660,3.377
Line 93: Biomedical Engineering,,97,,3.364,,197,3.361,,135,3.395,228,3.659,657,3.474
Line 94: Chemical Engineering,,59,,3.385,,103,3.340,,102,3.308,213,3.404,477,3.365
Line 95: Civil & Environmental Engrg,,54,,3.240,,68,3.146,,88,3.289,134,3.497,344,3.334
Line 96: Computer Engineering,,65,,3.228,,163,3.365,,141,3.381,203,3.500,572,3.399
Line 97: Electrical Engineering,,33,,3.253,,96,3.288,,123,3.260,183,3.473,435,3.350
Line 98: Engineering Mechanics,,27,,3.132,,55,3.294,,45,3.336,79,3.312,206,3.288
Line 99: Engineering Physics,,3,,,,14,3.515,,4,,10,3.302,31,3.494
Line 100: Engineering Undecided,,24,,3.038,,17,3.264,,5,,2,,48,3.192
Line 101: Environmental Engineering,,31,,3.188,,58,3.251,,33,3.344,29,3.627,151,3.333
Line 102: Geological Engineering,,3,,,,3,,,6,3.306,15,3.692,27,3.567
Line 103: Industrial Engineering,,28,,3.166,,61,3.422,,68,3.401,147,3.645,304,3.497
Line 104: Materials Science and Engr,,6,,2.747,,10,3.143,,23,3.334,58,3.499,97,3.371
Line 105: Mechanical Engineering,,175,,3.165,,316,3.262,,271,3.266,474,3.506,1236,3.338
Line 106: Nuclear Engineering,,12,,3.137,,12,2.869,,30,3.306,21,3.383,75,3.223
Line 107: FRESHMEN,,,,,SOPHOMORES,,,JUNIORS              SENIORS                   TOTAL,,,,,,
Line 108: Count,,,,GPA,,Count,GPA,,Count,GPA,Count,GPA,Count,GPA
Line 109: School/College Program         Undergraduate Men and Women by School/College,,,,,,,,,,,,,,
Line 110: Human Ecology,,269,,3.423,,521,3.509,,753,3.567,747,3.607,2290,3.550
Line 111: Human Ecology,,208,,3.425,,374,3.534,,502,3.595,473,3.619,1557,3.566
Line 112: Human Ecology Online,,,,,,2,,,7,3.112,30,3.567,39,3.489
Line 113: Interior Architecture,,,,,,16,3.895,,27,3.901,39,3.874,82,3.887
Line 114: Personal Finance,,35,,3.299,,108,3.349,,184,3.430,180,3.532,507,3.439
Line 115: Textiles and Fashion Design,,26,,3.579,,21,3.529,,33,3.648,25,3.518,105,3.577
Line 116: Letters and Science,,3151,,3.365,,4666,3.424,,5097,3.443,5783,3.534,18697,3.452
Line 117: Applied Math & Engr Physics,,2,,,,9,3.550,,17,3.414,22,3.359,50,3.416
Line 118: General Course - BA Degree,,1629,,3.382,,1852,3.440,,1956,3.468,1937,3.539,7374,3.460
Line 119: General Course - BS Degree,,1505,,3.343,,2676,3.401,,2886,3.403,3500,3.512,10567,3.429
Line 120: Journalism - BA Degree,,,,,,91,3.664,,181,3.707,220,3.756,492,3.720
Line 121: Journalism - BS Degree,,,,,,5,,,14,3.749,16,3.667,35,3.714
Line 122: Landscape Architecture,,3,,,,13,3.658,,19,3.710,27,3.506,62,3.610
Line 123: Letters & Science Online,,,,,,1,,,2,,4,,7,3.667
Line 124: Music,,7,,3.735,,7,3.573,,10,3.632,9,3.891,33,3.712
Line 125: Music Cert Prog,,5,,,,12,3.795,,9,3.816,6,3.940,32,3.827
Line 126: Social Work,,,,,,,,,3,,42,3.832,45,3.802
Line 127: Nursing,,172,,3.276,,192,3.350,,203,3.537,323,3.645,890,3.469
Line 128: Nursing Accelerated,,,,,,,,,,,43,3.562,43,3.562
Line 129: Nursing Collaborative Program,,,,,,,,,8,3.639,43,3.549,51,3.566
Line 130: Nursing Undergraduate,,,,,,,,,93,3.583,228,3.689,321,3.656
Line 131: Pre-Nursing,,172,,3.276,,192,3.350,,102,3.497,9,3.370,475,3.354
Line 132: Pharmacy,,,,,,,,,17,3.637,29,3.584,46,3.604
Line 133: Pharmacology & Toxicology,,,,,,,,,17,3.637,29,3.584,46,3.604
Line 134: Total,,5411,,3.350,,8464,3.403,,9709,3.444,11755,3.541,35339,3.451
Line 135: FRESHMEN,,,,,SOPHOMORES,,,JUNIORS              SENIORS                   TOTAL,,,,,,
Line 136: Count,,,,GPA,,Count,GPA,,Count,GPA,Count,GPA,Count,GPA
Line 137: School/College Program                      Undergraduate Men by School/College,,,,,,,,,,,,,,
Line 138: Agricultural and Life Sciences,,115,,3.217,,164,3.347,,266,3.329,353,3.387,898,3.340
Line 139: Agricultural & Life Sciences,,108,,3.217,,153,3.370,,236,3.382,299,3.423,796,3.372
Line 140: Agricultural Business Mgmt,,4,,,,4,,,9,2.943,8,3.090,25,3.102
Line 141: Biological Systems Engineering,,2,,,,3,,,16,2.940,41,3.138,62,3.054
Line 142: Dietetics,,1,,,,4,,,5,,5,,15,3.102
Line 143: Business,,239,,3.354,,470,3.405,,594,3.442,722,3.500,2025,3.444
Line 144: Business Online,,,,,,4,,,16,3.276,11,3.617,31,3.377
Line 145: Business Undergraduate,,239,,3.354,,466,3.407,,578,3.445,711,3.498,1994,3.444
Line 146: Education,,99,,3.306,,86,3.371,,117,3.578,152,3.607,454,3.489
Line 147: Art,,10,,3.636,,8,3.400,,16,3.694,18,3.707,52,3.642
Line 148: Art Education,,,,,,,,,1,,2,,3,
Line 149: Bachelor of Fine Arts,,,,,,,,,,,4,,4,
Line 150: Bachelor of Science - Dance,,2,,,,1,,,,,2,,5,
Line 151: Education Studies,,8,,3.131,,1,,,2,,12,3.552,23,3.415
Line 152: Elementary Education,,,,,,,,,11,3.801,19,3.836,30,3.822
Line 153: Elementary Special Education,,,,,,,,,,,2,,2,
Line 154: Health Promo and Health Equity,,5,,,,12,3.297,,11,3.576,12,3.705,40,3.473
Line 155: Kinesiology,,,,,,1,,,36,3.507,55,3.542,92,3.514
Line 156: Kines-Pre-Exer/Pre-Mtr Behvr,,59,,3.313,,45,3.402,,20,3.514,6,3.094,130,3.365
Line 157: Phy Ed - Pre-Phy Ed Tchr Prep,,1,,,,1,,,,,,,2,
Line 158: Physical Education,,,,,,2,,,9,3.238,8,3.432,19,3.313
Line 159: Pre-Art Education,,1,,,,,,,,,,,1,
Line 160: Pre-Elementary Education,,8,,3.054,,8,3.475,,2,,,,18,3.353
Line 161: Pre-Special Educ & Rehab Psy,,1,,,,2,,,,,,,3,
Line 162: Rehabilitation Psychology,,,,,,1,,,3,,3,,7,3.506
Line 163: Secondary Education,,1,,,,,,,,,,,1,
Line 164: Special Education,,,,,,,,,1,,2,,3,
Line 165: Theatre & Drama,,3,,,,4,,,5,,7,3.589,19,3.604
Line 166: Engineering,,449,,3.200,,827,3.295,,805,3.324,1279,3.509,3360,3.367
Line 167: Biomedical Engineering,,51,,3.395,,94,3.354,,65,3.416,103,3.637,313,3.466
Line 168: Chemical Engineering,,32,,3.473,,66,3.336,,65,3.300,128,3.414,291,3.375
Line 169: Civil & Environmental Engrg,,36,,3.171,,53,3.122,,54,3.304,85,3.510,228,3.318
Line 170: Computer Engineering,,59,,3.240,,135,3.388,,124,3.385,169,3.520,487,3.412
Line 171: Electrical Engineering,,25,,3.204,,76,3.308,,109,3.278,152,3.485,362,3.361
Line 172: Engineering Mechanics,,21,,3.143,,43,3.253,,39,3.321,69,3.364,172,3.297
Line 173: Engineering Physics,,2,,,,13,3.482,,4,,7,3.423,26,3.532
Line 174: Engineering Undecided,,18,,2.895,,9,3.238,,5,,2,,34,3.121
Line 175: Environmental Engineering,,15,,3.025,,18,3.344,,16,3.401,7,3.595,56,3.309
Line 176: Geological Engineering,,2,,,,1,,,1,,7,3.762,11,3.619
Line 177: Industrial Engineering,,20,,3.041,,38,3.385,,41,3.353,97,3.634,196,3.462
Line 178: Materials Science and Engr,,5,,,,7,3.082,,19,3.293,38,3.515,69,3.338
Line 179: Mechanical Engineering,,152,,3.168,,263,3.255,,240,3.280,397,3.498,1052,3.335
Line 180: FRESHMEN,,,,,SOPHOMORES,,,JUNIORS              SENIORS                   TOTAL,,,,,,
Line 181: Count,,,,GPA,,Count,GPA,,Count,GPA,Count,GPA,Count,GPA
Line 182: School/College Program                      Undergraduate Men by School/College,,,,,,,,,,,,,,
Line 183: Nuclear Engineering,,11,,3.080,,11,2.813,,23,3.329,18,3.384,63,3.205
Line 184: Human Ecology,,56,,3.193,,136,3.397,,239,3.396,256,3.461,687,3.403
Line 185: Human Ecology,,28,,3.154,,61,3.408,,104,3.437,98,3.426,291,3.401
Line 186: Human Ecology Online,,,,,,1,,,4,,17,3.641,22,3.488
Line 187: Interior Architecture,,,,,,1,,,,,2,,3,
Line 188: Personal Finance,,26,,3.227,,70,3.353,,129,3.372,135,3.479,360,3.397
Line 189: Textiles and Fashion Design,,2,,,,3,,,2,,4,,11,3.468
Line 190: Letters and Science,,1395,,3.332,,2237,3.400,,2471,3.385,2918,3.456,9021,3.402
Line 191: Applied Math & Engr Physics,,1,,,,6,3.676,,14,3.468,19,3.398,40,3.469
Line 192: General Course - BA Degree,,608,,3.324,,742,3.388,,735,3.366,767,3.417,2852,3.376
Line 193: General Course - BS Degree,,778,,3.334,,1450,3.399,,1672,3.390,2054,3.463,5954,3.409
Line 194: Journalism - BA Degree,,,,,,22,3.626,,31,3.486,45,3.664,98,3.597
Line 195: Journalism - BS Degree,,,,,,3,,,4,,7,3.580,14,3.533
Line 196: Landscape Architecture,,,,,,5,,,8,3.435,13,3.549,26,3.524
Line 197: Letters & Science Online,,,,,,,,,,,3,,3,
Line 198: Music,,5,,,,4,,,5,,4,,18,3.581
Line 199: Music Cert Prog,,3,,,,5,,,2,,3,,13,3.778
Line 200: Social Work,,,,,,,,,,,3,,3,
Line 201: Nursing,,15,,3.371,,27,3.171,,31,3.481,56,3.575,129,3.433
Line 202: Nursing Accelerated,,,,,,,,,,,9,3.627,9,3.627
Line 203: Nursing Collaborative Program,,,,,,,,,1,,9,3.725,10,3.696
Line 204: Nursing Undergraduate,,,,,,,,,13,3.401,36,3.526,49,3.490
Line 205: Pre-Nursing,,15,,3.371,,27,3.171,,17,3.534,2,,61,3.341
Line 206: Pharmacy,,,,,,,,,5,,13,3.630,18,3.612
Line 207: Pharmacology & Toxicology,,,,,,,,,5,,13,3.630,18,3.612
Line 208: Total,,2368,,3.298,,3947,3.373,,4528,3.384,5749,3.475,16592,3.400
Line 209: FRESHMEN      SOPHOMORES         JUNIORS              SENIORS                   TOTAL,,,,,,,,,,,,,,
Line 210: Count,,,,GPA,,Count,GPA,,Count,GPA,Count,GPA,Count,GPA
Line 211: School/College Program                   Undergraduate Women by School/College,,,,,,,,,,,,,,
Line 212: Agricultural and Life Sciences,,288,,3.356,,468,3.264,,616,3.343,747,3.488,2119,3.377
Line 213: Agricultural & Life Sciences,,265,,3.349,,433,3.283,,540,3.354,676,3.492,1914,3.385
Line 214: Agricultural Business Mgmt,,3,,,,4,,,10,3.181,7,3.296,24,3.035
Line 215: Biological Systems Engineering,,8,,3.477,,5,,,22,3.155,22,3.291,57,3.256
Line 216: Dietetics,,12,,3.503,,26,3.113,,44,3.346,42,3.563,124,3.384
Line 217: Business,,188,,3.351,,356,3.412,,489,3.410,601,3.575,1634,3.463
Line 218: Business Online,,,,,,4,,,30,3.105,20,3.436,54,3.262
Line 219: Business Undergraduate,,188,,3.351,,352,3.410,,459,3.424,581,3.577,1580,3.467
Line 220: Education,,273,,3.505,,368,3.535,,483,3.696,502,3.743,1626,3.642
Line 221: Art,,37,,3.550,,51,3.698,,47,3.752,57,3.770,192,3.705
Line 222: Art Education,,,,,,,,,7,3.505,17,3.736,24,3.670
Line 223: Bachelor of Fine Arts,,,,,,,,,,,8,3.864,8,3.864
Line 224: Bachelor of Fine Arts - Dance,,1,,,,,,,1,,3,,5,
Line 225: Bachelor of Science - Dance,,18,,3.751,,14,3.394,,5,,11,3.822,48,3.658
Line 226: Education Studies,,12,,3.178,,17,3.476,,16,3.681,31,3.687,76,3.567
Line 227: Elementary Education,,,,,,1,,,107,3.955,93,3.926,201,3.941
Line 228: Elementary Special Education,,,,,,,,,,,22,3.980,22,3.980
Line 229: Health Promo and Health Equity,,13,,3.690,,36,3.554,,84,3.664,85,3.570,218,3.612
Line 230: Kinesiology,,,,,,1,,,68,3.491,100,3.637,169,3.577
Line 231: Kines-Pre-Exer/Pre-Mtr Behvr,,87,,3.433,,88,3.332,,58,3.534,1,,234,3.423
Line 232: Phy Ed - Pre-Phy Ed Tchr Prep,,2,,,,,,,,,,,2,
Line 233: Physical Education,,1,,,,3,,,4,,11,3.774,19,3.570
Line 234: Pre-Art Education,,3,,,,7,3.642,,8,3.729,2,,20,3.658
Line 235: Pre-ElemEdu Spec Edu,,2,,,,1,,,,,,,3,
Line 236: Pre-Elementary Education,,67,,3.469,,95,3.575,,16,3.635,,,178,3.542
Line 237: Pre-Special Educ & Rehab Psy,,8,,3.761,,13,3.743,,3,,,,24,3.753
Line 238: Rehabilitation Psychology,,11,,3.557,,32,3.658,,38,3.657,36,3.746,117,3.675
Line 239: Secondary Education,,,,,,2,,,8,3.803,11,3.763,21,3.773
Line 240: Special Education,,,,,,,,,9,3.489,5,,14,3.662
Line 241: Theatre & Drama,,11,,3.630,,7,3.524,,4,,9,3.611,31,3.588
Line 242: Engineering,,168,,3.306,,346,3.323,,269,3.318,517,3.534,1300,3.402
Line 243: Biomedical Engineering,,46,,3.328,,103,3.368,,70,3.375,125,3.677,344,3.480
Line 244: Chemical Engineering,,27,,3.283,,37,3.348,,37,3.321,85,3.389,186,3.351
Line 245: Civil & Environmental Engrg,,18,,3.374,,15,3.233,,34,3.262,49,3.474,116,3.366
Line 246: Computer Engineering,,6,,3.100,,28,3.260,,17,3.353,34,3.409,85,3.327
Line 247: Electrical Engineering,,8,,3.404,,20,3.207,,14,3.126,31,3.414,73,3.297
Line 248: Engineering Mechanics,,6,,3.091,,12,3.436,,6,3.429,10,2.940,34,3.244
Line 249: Engineering Physics,,1,,,,1,,,,,3,,5,
Line 250: Engineering Undecided,,6,,3.459,,8,3.294,,,,,,14,3.367
Line 251: Environmental Engineering,,16,,3.342,,40,3.210,,17,3.290,22,3.638,95,3.346
Line 252: Geological Engineering,,1,,,,2,,,5,,8,3.649,16,3.537
Line 253: Industrial Engineering,,8,,3.483,,23,3.484,,27,3.473,50,3.666,108,3.562
Line 254: FRESHMEN      SOPHOMORES         JUNIORS              SENIORS                   TOTAL,,,,,,,,,,,,,,
Line 255: Count,,,,GPA,,Count,GPA,,Count,GPA,Count,GPA,Count,GPA
Line 256: School/College Program                   Undergraduate Women by School/College,,,,,,,,,,,,,,
Line 257: Materials Science and Engr,,1,,,,3,,,4,,20,3.470,28,3.450
Line 258: Mechanical Engineering,,23,,3.148,,53,3.297,,31,3.157,77,3.547,184,3.353
Line 259: Nuclear Engineering,,1,,,,1,,,7,3.222,3,,12,3.329
Line 260: Human Ecology,,213,,3.484,,385,3.546,,514,3.642,491,3.680,1603,3.610
Line 261: Human Ecology,,180,,3.468,,313,3.557,,398,3.635,375,3.670,1266,3.603
Line 262: Human Ecology Online,,,,,,1,,,3,,13,3.480,17,3.489
Line 263: Interior Architecture,,,,,,15,3.920,,27,3.901,37,3.870,79,3.891
Line 264: Personal Finance,,9,,3.488,,38,3.341,,55,3.564,45,3.687,147,3.538
Line 265: Textiles and Fashion Design,,24,,3.599,,18,3.461,,31,3.654,21,3.594,94,3.589
Line 266: Letters and Science,,1756,,3.391,,2429,3.446,,2626,3.497,2865,3.610,9676,3.498

I convereted the excel file into csv for easier manipulation of data.. it was very hard to understand anything from the excel. 
I made it into a data frame but there is one significant problem right now:
    - there is no clear split between teh data if u can see in the dataframe, it just random data, so we have to figure out a way to split the data atleaset by grade level. I tried the /n method, we now have to extract the lines we want from there.

In [18]:
df.shape

(266, 15)

In [19]:
df.columns

Index(['AVERAGE Semester UNDERGRADUATE GRADE POINT AVERAGES\nUNIVERSITY OF WISCONSIN-MADISON\nFIRST SEMESTER 2023-2024\nJun 18, 2024',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10',
       'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14'],
      dtype='object')

In [20]:
df.describe

<bound method NDFrame.describe of     AVERAGE Semester UNDERGRADUATE GRADE POINT AVERAGES\nUNIVERSITY OF WISCONSIN-MADISON\nFIRST SEMESTER 2023-2024\nJun 18, 2024  \
0    Grade point average is calculated by dividing ...
1                                                  NaN
2    Only the letter grades A, AB, B, BC, C, D, and...
3    This report prepared by the Office of the Regi...
4                                             FRESHMEN
..                                                 ...
261                              Nursing Undergraduate
262                                        Pre-Nursing
263                                           Pharmacy
264                          Pharmacology & Toxicology
265                                              Total

                                            Unnamed: 1  Unnamed: 2  \
0                                                  NaN         NaN
1    Letter Grades A = Excellent\nAB = Intermediate...         NaN
2                                                  NaN         NaN
3                                                  NaN         NaN
4                                                  NaN         NaN
..                                                 ...         ...
261                                                NaN         NaN
262                                                NaN       157.0
263                                                NaN         NaN
264                                                NaN         NaN
265                                                NaN      3043.0

                                            Unnamed: 3 Unnamed: 4  Unnamed: 5  \
0                                                  NaN        NaN         NaN
1    Grade Points Per Credit\n4.0\n3.5\n3.0\n2.5\n2...        NaN         NaN
2                                                  NaN        NaN         NaN
3                                                  NaN        NaN         NaN
4                                                  NaN        NaN  SOPHOMORES
..                                                 ...        ...         ...
261                                                NaN        NaN         NaN
262                                                NaN      3.266         NaN
263                                                NaN        NaN         NaN
264                                                NaN        NaN         NaN
265                                                NaN      3.391         NaN

    Unnamed: 6 Unnamed: 7                                         Unnamed: 8  \
0          NaN        NaN                                                NaN
1          NaN        NaN                                                NaN
2          NaN        NaN                                                NaN
3          NaN        NaN                                                NaN
4          NaN        NaN  JUNIORS              SENIORS                  ...
..         ...        ...                                                ...
261        NaN        NaN                                                NaN
262        165      3.378                                                NaN
263        NaN        NaN                                                NaN
264        NaN        NaN                                                NaN
265       4517      3.428                                                NaN

    Unnamed: 9 Unnamed: 10 Unnamed: 11 Unnamed: 12 Unnamed: 13 Unnamed: 14
0          NaN         NaN         NaN         NaN         NaN         NaN
1          NaN         NaN         NaN         NaN         NaN         NaN
2          NaN         NaN         NaN         NaN         NaN         NaN
3          NaN         NaN         NaN         NaN         NaN         NaN
4          NaN         NaN         NaN         NaN         NaN         NaN
..         ...         ...         ...         ...         ...         ...
261         80       3.612         192       3.719         272       3.685
262         85       3.490           7       3.282         414       3.356
263         12       3.668          16       3.547          28       3.598
264         12       3.668          16       3.547          28       3.598
265       5181       3.496        6006       3.603       18747       3.496

[266 rows x 15 columns]>

In [21]:
df.info

<bound method DataFrame.info of     AVERAGE Semester UNDERGRADUATE GRADE POINT AVERAGES\nUNIVERSITY OF WISCONSIN-MADISON\nFIRST SEMESTER 2023-2024\nJun 18, 2024  \
0    Grade point average is calculated by dividing ...
1                                                  NaN
2    Only the letter grades A, AB, B, BC, C, D, and...
3    This report prepared by the Office of the Regi...
4                                             FRESHMEN
..                                                 ...
261                              Nursing Undergraduate
262                                        Pre-Nursing
263                                           Pharmacy
264                          Pharmacology & Toxicology
265                                              Total

                                            Unnamed: 1  Unnamed: 2  \
0                                                  NaN         NaN
1    Letter Grades A = Excellent\nAB = Intermediate...         NaN
2                                                  NaN         NaN
3                                                  NaN         NaN
4                                                  NaN         NaN
..                                                 ...         ...
261                                                NaN         NaN
262                                                NaN       157.0
263                                                NaN         NaN
264                                                NaN         NaN
265                                                NaN      3043.0

                                            Unnamed: 3 Unnamed: 4  Unnamed: 5  \
0                                                  NaN        NaN         NaN
1    Grade Points Per Credit\n4.0\n3.5\n3.0\n2.5\n2...        NaN         NaN
2                                                  NaN        NaN         NaN
3                                                  NaN        NaN         NaN
4                                                  NaN        NaN  SOPHOMORES
..                                                 ...        ...         ...
261                                                NaN        NaN         NaN
262                                                NaN      3.266         NaN
263                                                NaN        NaN         NaN
264                                                NaN        NaN         NaN
265                                                NaN      3.391         NaN

    Unnamed: 6 Unnamed: 7                                         Unnamed: 8  \
0          NaN        NaN                                                NaN
1          NaN        NaN                                                NaN
2          NaN        NaN                                                NaN
3          NaN        NaN                                                NaN
4          NaN        NaN  JUNIORS              SENIORS                  ...
..         ...        ...                                                ...
261        NaN        NaN                                                NaN
262        165      3.378                                                NaN
263        NaN        NaN                                                NaN
264        NaN        NaN                                                NaN
265       4517      3.428                                                NaN

    Unnamed: 9 Unnamed: 10 Unnamed: 11 Unnamed: 12 Unnamed: 13 Unnamed: 14
0          NaN         NaN         NaN         NaN         NaN         NaN
1          NaN         NaN         NaN         NaN         NaN         NaN
2          NaN         NaN         NaN         NaN         NaN         NaN
3          NaN         NaN         NaN         NaN         NaN         NaN
4          NaN         NaN         NaN         NaN         NaN         NaN
..         ...         ...         ...         ...         ...         ...
261         80       3.612         192       3.719         272       3.685
262         85       3.490           7       3.282         414       3.356
263         12       3.668          16       3.547          28       3.598
264         12       3.668          16       3.547          28       3.598
265       5181       3.496        6006       3.603       18747       3.496

[266 rows x 15 columns]>

In [22]:
df.isnull().sum()

AVERAGE Semester UNDERGRADUATE GRADE POINT AVERAGES\nUNIVERSITY OF WISCONSIN-MADISON\nFIRST SEMESTER 2023-2024\nJun 18, 2024      1
Unnamed: 1                                                                                                                      265
Unnamed: 2                                                                                                                       89
Unnamed: 3                                                                                                                      265
Unnamed: 4                                                                                                                      124
Unnamed: 5                                                                                                                      262
Unnamed: 6                                                                                                                       61
Unnamed: 7                                                                                                                      108
Unnamed: 8                                                                                                                      262
Unnamed: 9                                                                                                                       44
Unnamed: 10                                                                                                                      82
Unnamed: 11                                                                                                                      35
Unnamed: 12                                                                                                                      64
Unnamed: 13                                                                                                                      21
Unnamed: 14                                                                                                                      41
dtype: int64

In [16]:
df['Unnamed: 1']

0                                                    NaN
1      Letter Grades A = Excellent\nAB = Intermediate...
2                                                    NaN
3                                                    NaN
4                                                    NaN
                             ...
261                                                  NaN
262                                                  NaN
263                                                  NaN
264                                                  NaN
265                                                  NaN
Name: Unnamed: 1, Length: 266, dtype: object

In [23]:
numeric_data = df.select_dtypes(include=['number'])
numeric_data.columns.tolist()
numeric_data

     Unnamed: 2
0           NaN
1           NaN
2           NaN
3           NaN
4           NaN
..          ...
261         NaN
262       157.0
263         NaN
264         NaN
265      3043.0

[266 rows x 1 columns]

In [15]:
df['Unnamed: 1'].fillna(df['Unnamed: 1'].mean(),inplace=False)
# # df['U'].fillna(df['column_name'].mean(), inplace=True)
# df['Unnamed: 2'].fillna(df['Unnamed: 2'].mean(),inplace=False)
# df['Unnamed: 3'].fillna(df['Unnamed: 3'].mean(),inplace=False)
# df['Unnamed: 4'].fillna(df['Unnamed: 4'].mean(),inplace=False)
# df['Unnamed: 5'].fillna(df['Unnamed: 5'].mean(),inplace=False)
# df['Unnamed: 6'].fillna(df['Unnamed: 6'].mean(),inplace=False)
# df['Unnamed: 7'].fillna(df['Unnamed: 7'].mean(),inplace=False)
# df['Unnamed: 8'].fillna(df['Unnamed: 8'].mean(),inplace=False)
# df['Unnamed: 9'].fillna(df['Unnamed: 9'].mean(),inplace=False)

NameError: name 'Unnamed' is not defined